mybatis:
  mapper-locations: classpath:Mappers/*.xml #标识Mapper配置文件位置
  type-aliases-package: com.xielaoban.cqueshop.Entity #设置包别名，设置之后在xml可以直接写实体类名

spring:
  #数据库相关
  datasource:
    username: root
    password: 1210579586
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接池相关
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
    #redis缓存相关
  redis:
    #Redis服务器地址
    host: localhost
    #Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    jedis:
      pool:
        max-active: 50 #连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 20 #连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
    timeout: 5000 #连接超时时间（毫秒）
  #多配置文件
  profiles:
    active: pathInfo
  devtools:
    restart:
      enabled: true #开启热部署
      additional-paths: src/main/java #热部署目录
  freemarker:
    cache: false #页面不加载缓存
logging:
  level:
    com.xielaoban.cqueshop: debug
  file:
    path: 'D:/myshop/log'
  pattern:
    file: '%d{yyyy-MM-dd hh-MM-ss} - [%thread] - %-5level - %logger{50} - %msg%n'

server:
  port: 8888
  servlet:
    context-path: /shop
